### ISSUE TITLE
Full usage example?

### ISSUE THREAD

**Issue by lrhazi** [typesafehub/scalalogging#18]
How do I use this module? Any link to example source would be very appreciated.

**Comment by hseeberger** [comment]
The [README](https://github.com/typesafehub/scalalogging/) contains all the steps to get started:

First you have to depend on the library, e.g. for sbt 

```
libraryDependencies += "com.typesafe" %% "scalalogging-slf4j" % "1.0.1"
```

Then simply start coding, e.g.

```
class MyClass extends Logging {
  logger.debug("This is very convenient ;-)")
}
```

The test projects may also provide some insight, e.g. https://github.com/typesafehub/scalalogging/blob/master/scalalogging-slf4j-test/src/test/scala/com/typesafe/scalalogging/slf4j/Slf4jLoggerSpec.scala
