### ISSUE TITLE
macros are unnecessary

### ISSUE THREAD

**Issue by infinity0** [typesafehub/scalalogging#19]
scalalogging could provide logger methods that take a (Unit => String) rather than a String, then we don't need macros:

```
logger.debug(() => s"Some ${expensiveExpression} message!")
```

**Comment by hseeberger** [comment]
No. First it is inconvenient to write lambdas instead of simple strings. Second we want to avoid the creation of the runtime objects for the lambdas. What you suggest is a first yet immature step towards convenient and performant logging.

**Comment by infinity0** [comment]
I don't think the first/second reasons are significant, compared to the additional level of complexity that macros introduce into the build process, and the potential abuse they can open the rest of the code to. What is the harm in giving users the _option_ to do this? Wrapping something inside a function is a very natural way to delay evaluation, especially in the functional programming style.

**Comment by hseeberger** [comment]
Macros only impose additional complexity to the library author. You can use ScalaLogging just by depending on it like on any other library. So you get convenience and performance for free.

**Comment by hseeberger** [comment]
Closed because out of scope: This is a marco based library!

**Comment by infinity0** [comment]
OK, thanks for the explanation. I admit I have not looked too closely into exactly how this library works. As long as the macro features are not enabled in my code, I am happy. And it's good to talk about this issue because I'm sure someone else would bring it up in the future otherwise. :)

**Comment by infinity0** [comment]
I just remembered about Scala's call-by-name feature today, where you declare the function as `def log(msg: => String)` and `msg` will only be evaluated if it's actually used in the function. How does this compare to using macros?

**Comment by hseeberger** [comment]
How do you think by-name parameters are implemented under the hood? As the JVM only offers call-site evaluation, the Scala compiler transforms a by-name argument into a arity-0 function at call-site and applies that function at receiver-site. Therefore by-name parameters impose a certain overhead, namely the creation of the function value.

Macros simply inline the "most lightweight" code at call-site, i.e. you get the best performance.
