### ISSUE TITLE
Upgrade SLF4J 1.7.5

### ISSUE THREAD

**Issue by analytically** [typesafehub/scalalogging#21]
Given the raison d'être of scalalogging is performance, you're likely happy to learn that SLF4J 1.7.5 is a performance release, hence I think it should be included in the next scalalogging release.

http://www.slf4j.org/news.html
"The logger factories in most SLF4J modules namely in jcl-over-slf4j, log4j-over-slf4j, slf4j-jcl, slf4j-jdk14, slf4j-log4j12, and slf4j-simple now use a ConcurrentHashMap instead of a regular HashMap to cache logger instances. This change significantly improves logger retrieval times at the cost of some memory overhead. This improvement was requested in bug #298 by Taras Tielkes who also provided the relevant patch."

**Comment by hseeberger** [comment]
Thanks for reporting!
A new snapshot 1.1.0-SNAPSHOT has been published.

**Comment by analytically** [comment]
Release 1.1.0?
