### ISSUE TITLE
How to change log level

### ISSUE THREAD

**Issue by java-developer** [typesafehub/scalalogging#22]
Hello,

I'm just getting started with Scala and want to use your library for logging.

I've followed the README and am able to see INFO log messages (e.g. logger.info("hello!")) in the console but when I change my log messages to any other level (e.g. logger.debug("hello!")) I don't see them.

I tried adding

logLevel in Global := Level.Debug

to my build.sbt and I get a lot more console output from the Scala libraries but nothing from my code.

What am I missing?

Thanks!

**Comment by hseeberger** [comment]
The sbt logLevel setting is not at all related to the log levels of SLF4J or Log4j. Please go to these libraries and learn how to configure logging.

**Comment by craignicoll** [comment]
Maybe you should say that in the README.
