### ISSUE TITLE
Have Logging and StrictLogging extend an common abstract trait

### ISSUE THREAD

**Issue by blair** [typesafehub/scalalogging#24]
We have abstract classes that want a logger mixed into it but don't care if it comes from Logging or StrictLogging, so adding a common ancestor would be nice:

```
trait HasLogging {
  protected val logger: Logger
}

trait Logging extends HasLogging {
...
}

trait StrictLogging extends HasLogging {
...
}
```

**Comment by hseeberger** [comment]
Good one!

**Comment by hseeberger** [comment]
1.1.0-SNAPSHOT published to Sonatype OSS. Please try in anger and let me know any issues. Happy to release 1.1.0 (RC) if you give me thumbs up.

**Comment by analytically** [comment]
Works fine for me. +1 on a 1.1.0 release.

**Comment by blair** [comment]
For self-types to work, Logging and StrictLogging need to extend AbstractLogging:

```
import com.typesafe.scalalogging.slf4j.{
  AbstractLogging,
  StrictLogging
}

trait NeedsLogging {
  self: AbstractLogging =>
}

class Foo extends NeedsLogging with StrictLogging {
}
```

gets this compile failure:

```
[info] Formatting 1 Scala source {file:/tmp/blair/}default-6dbc03(compile) ...
[info] Compiling 1 Scala source to /tmp/blair/target/scala-2.10/classes...
[error] /tmp/blair/src/main/scala/Test.scala:12: illegal inheritance;
[error]  self-type Foo does not conform to NeedsLogging's selftype NeedsLogging with com.typesafe.scalalogging.slf4j.AbstractLogging
[error] class Foo extends NeedsLogging with StrictLogging {
[error]                   ^
[error] one error found
[error] (compile:compile) Compilation failed
```

**Comment by blair** [comment]
In fact, you could move AbstractLogging above the SLF4J package and have both the SLF4J and log4j traits extend that.

This would provide allow one to provide a Scala library of traits that declare a self type on AbstractLogging and the end application developer would pick the logging implementation when they declare the concrete class by mixing in SLF4J or log4j's trait.

**Comment by hseeberger** [comment]
Oops, I forgot to extend AbstractLogging for the slf4j module (for log4j I did it right).

**Comment by hseeberger** [comment]
OK, I published a new snapshot. Please give it a spin.

**Comment by blair** [comment]
I did a `sbt update` and the compile succeeded.

Thanks!

**Comment by blair** [comment]
BTW, is this considered an ABI change, in which case the version number should go to 2.0.0?

**Comment by hseeberger** [comment]
Is it? Could you please elaborate?

**Comment by blair** [comment]
According to this, there will be no compatibility issues [1]:

```
Changing the direct superclass or the set of direct superinterfaces of a class type will not break compatibility with pre-existing binaries, provided that the total set of superclasses or superinterfaces, respectively, of the class type loses no members.
```

[1] http://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html#jls-13.4.4
