### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by jpswain** [typesafehub/scalalogging#26]
I have this in resolvers:
                "Typesafe Repository" at "http://repo.typesafe.com/typesafe/releases/"

and these two in libraryDependencies:
    "com.typesafe" %% "scalalogging-slf4j" % "1.0.1",
    "com.typesafe" %% "scalalogging-log4j" % "1.0.1"

I still get this:
Failed to load class "org.slf4j.impl.StaticLoggerBinder", but according to the wiki here, only those 2 are needed.  Did I miss something?

**Comment by hseeberger** [comment]
First, you should either use SLF4J or Log4j, not both. Second, in addition to scalalogging, you need the respective logging implementation. In the case of SLF4J this could be Logback. Please refer to the SLF4J or Log4j documentation.

By the way, you don't need the "Typesafe Repository" resolver.

**Comment by jpswain** [comment]
Ah thanks!  I got it working like this (in case anyone as clueless as me stops by here):

```
"com.typesafe" %% "scalalogging-slf4j" % "1.0.1",
"org.slf4j" % "slf4j-api" % "1.7.1",
"org.slf4j" % "log4j-over-slf4j" % "1.7.1",  // for any java classes looking for this
"ch.qos.logback" % "logback-classic" % "1.0.3"
```

**Comment by pvorb** [comment]
@hseeberger It would be great if you could give a hint on that in the README.

**Comment by PatrickHuang888** [comment]
Yes, I met this either, I think it should be written in README. or I would think scala-logging include logging impl.

**Comment by mantovani** [comment]
Thank you very much

**Comment by jubins** [comment]
Adding below in scala project's `build.sbt` took care of this warning for me
```
libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.1.3" % Runtime
```

**Comment by jubins** [comment]
Adding below in scala project's `build.sbt` took care of this warning for me (just incase anyone wondering)
```
libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.1.3" % Runtime
```
