### ISSUE TITLE
Upgrade to Scala 2.10.2

### ISSUE THREAD

**Issue by igozali** [typesafehub/scalalogging#31]

**Comment by hseeberger** [comment]
There's no need to upgrade to 2.10.2, because all 2.10.x versions are binary compatible, i.e. you can use ScalaLogging build against 2.10.1 in a project of yours using 2.10.2 or any other 2.10.x version.

**Comment by igozali** [comment]
I assume some of the dependencies in scalalogging (I believe it's the reflection library) gives me these warnings when trying to compile a Maven project using this framework.

[WARNING]  Expected all dependencies to require Scala version: 2.10.2
[WARNING]  com.somegroup:some-maven-project:0.0.1 requires scala version: 2.10.2
[WARNING]  org.scala-lang:scala-reflect:2.10.0 requires scala version: 2.10.0
