### ISSUE TITLE
Fix the use of scalalogging with `-Yrangepos`

### ISSUE THREAD

**Issue by etorreborre** [typesafehub/scalalogging#38]
We had [this issue](https://github.com/etorreborre/specs2/issues/213) in specs2 where Scalalogging was used with the `-Yrangepos` compiler option. 

I suspect that the macros in Scalalogging need a bit of position setting to make this disappear.

**Comment by analytically** [comment]
+1

**Comment by etorreborre** [comment]
Closing this old issue now.
